/**
 * Org Mode Performance Data Seeder
 *
 * Seeds PostgreSQL database with test data for org-mode UI performance tests.
 * Wraps the k6 seed scripts to run them automatically from Playwright tests.
 *
 * This avoids the need to run `npm run k6:seed:all` manually before tests.
 */

import { execSync } from 'child_process';
import * as path from 'path';
import * as fs from 'fs';
import { fileURLToPath } from 'url';
import { Page } from '@playwright/test';
import { TEST_CREDENTIALS, TEST_USER_POOL } from '../../k6/src/config/constants.js';
import { RegistrationPage } from '../../pages/RegistrationPage.js';
import { OrganizationPage } from '../../pages/OrganizationPage.js';
import { DEBUG } from './performanceUtils.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Re-export credentials for backward compatibility (SSOT: k6 constants)
export const K6_USER_EMAIL = TEST_CREDENTIALS.EMAIL;
export const K6_USER_PASSWORD = TEST_CREDENTIALS.PASSWORD;

/**
 * Get a test user from the pool based on test name.
 * Distributes tests across users to avoid rate limiting (3 logins/min per email).
 * Uses simple hash of test name for consistent user assignment.
 *
 * @param testName - Unique test identifier (e.g., 'perf-history', 'perf-sign-all')
 * @returns User credentials from the pool
 */
export function getPooledTestUser(testName: string): { email: string; password: string } {
  // Simple hash: sum of char codes mod pool size
  const hash = testName.split('').reduce((sum, char) => sum + char.charCodeAt(0), 0);
  const index = hash % TEST_USER_POOL.length;
  return TEST_USER_POOL[index];
}

interface SeedResult {
  userCreated: boolean;
  transactionsSeeded: boolean;
  mnemonicPath: string | null;
}

/**
 * Seed the PostgreSQL database with k6 test user and transactions.
 * Equivalent to running: npm run k6:seed:all
 *
 * This function:
 * 1. Creates the k6 test user if not exists
 * 2. Seeds transactions (sign, history, approve)
 * 3. Generates mnemonic for Account Setup import
 */
export async function seedOrgPerfData(): Promise<SeedResult> {
  const automationDir = path.resolve(__dirname, '../..');
  const mnemonicPath = path.join(__dirname, '../../k6/data/test-mnemonic.txt');

  if (DEBUG) console.log('Seeding org-mode performance test data...');

  try {
    if (DEBUG) console.log('  Creating pool users...');
    execSync('npx tsx k6/helpers/seed-test-users.ts', {
      cwd: automationDir,
      stdio: 'inherit',
      env: {
        ...process.env,
        SEED_POOL: 'true',
      },
    });

    if (DEBUG) console.log('  Seeding transactions for all pool users...');
    execSync('npx tsx k6/helpers/seed-perf-data.ts', {
      cwd: automationDir,
      stdio: 'inherit',
      env: {
        ...process.env,
        SEED_POOL: 'true',
      },
    });

    if (!fs.existsSync(mnemonicPath)) {
      throw new Error(`Mnemonic file not found at ${mnemonicPath}`);
    }

    if (DEBUG) console.log('  Org-mode data seeding complete!');

    return {
      userCreated: true,
      transactionsSeeded: true,
      mnemonicPath,
    };
  } catch (error) {
    console.error('Error seeding org-mode data:', error);
    throw error;
  }
}

/**
 * Read the mnemonic generated by the seed script.
 * Returns array of 24 words.
 */
export function readSeedMnemonic(): string[] {
  const mnemonicPath = path.join(__dirname, '../../k6/data/test-mnemonic.txt');

  if (!fs.existsSync(mnemonicPath)) {
    throw new Error(
      `Mnemonic file not found. Run seedOrgPerfData() first or: npm run k6:seed:all`,
    );
  }

  const mnemonic = fs.readFileSync(mnemonicPath, 'utf-8').trim();
  const words = mnemonic.split(' ');

  if (words.length !== 24) {
    throw new Error(`Invalid mnemonic: expected 24 words, got ${words.length}`);
  }

  return words;
}

/**
 * Check if org-mode seed data exists (quick check without re-seeding)
 */
export function isOrgDataSeeded(): boolean {
  const mnemonicPath = path.join(__dirname, '../../k6/data/test-mnemonic.txt');
  return fs.existsSync(mnemonicPath);
}

/**
 * Import the seed mnemonic via the Recovery Phrase import flow.
 * Extracts duplicated mnemonic import logic from org-mode tests (DRY).
 */
export async function importSeedMnemonic(
  window: Page,
  registrationPage: RegistrationPage,
): Promise<void> {
  await registrationPage.waitForElementToBeVisible(registrationPage.createNewTabSelector);
  if (DEBUG) console.log('Account Setup screen visible, importing seed mnemonic...');

  const words = readSeedMnemonic();
  if (DEBUG) console.log(`Read mnemonic with ${words.length} words`);

  await registrationPage.clickOnImportTab();

  for (let i = 0; i < 24; i++) {
    await registrationPage.fillRecoveryPhraseWord(i + 1, words[i]);
  }

  await registrationPage.scrollToNextImportButton();
  await registrationPage.clickOnNextImportButton();

  // Wait for Key Pairs screen (button-next-import disappears)
  await window.waitForSelector('[data-testid="button-next-import"]', { state: 'hidden', timeout: 10000 });
  if (DEBUG) console.log('On Key Pairs screen');

  await registrationPage.waitForElementToDisappear(registrationPage.toastMessageSelector);
  await registrationPage.clickOnFinalNextButtonWithRetry();
  if (DEBUG) console.log('Account Setup completed');
}

/**
 * Full org-mode test environment setup.
 * Extracts duplicated setup logic from org-mode tests (DRY).
 *
 * This function:
 * 1. Seeds org data (user + transactions + mnemonic)
 * 2. Registers locally with unique email
 * 3. Connects to organization and signs in as k6 user
 * 4. Imports the seed mnemonic to complete Account Setup
 */
export async function setupOrgModeTestEnvironment(
  window: Page,
  registrationPage: RegistrationPage,
  organizationPage: OrganizationPage,
  testNamePrefix: string,
): Promise<void> {
  await seedOrgPerfData();

  const localPassword = 'TestPassword123';
  await registrationPage.completeRegistration(
    `${testNamePrefix}-${Date.now()}@test.com`,
    localPassword,
  );

  // Uses different email per test to avoid backend rate limiting (3 logins/min per email)
  const pooledUser = getPooledTestUser(testNamePrefix);
  await organizationPage.setupOrganization();
  await organizationPage.waitForElementToBeVisible(
    organizationPage.emailForOrganizationInputSelector,
  );
  await organizationPage.signInOrganization(pooledUser.email, pooledUser.password, localPassword);

  await importSeedMnemonic(window, registrationPage);
}
