/**
 * Org Mode Performance Data Seeder
 *
 * Seeds PostgreSQL database with test data for org-mode UI performance tests.
 * Wraps the k6 seed scripts to run them automatically from Playwright tests.
 *
 * This avoids the need to run `npm run k6:seed:all` manually before tests.
 */

import { execSync } from 'child_process';
import * as path from 'path';
import * as fs from 'fs';
import { fileURLToPath } from 'url';
import { createClient } from 'redis';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// k6 test user credentials
export const K6_USER_EMAIL = 'k6perf@test.com';
export const K6_USER_PASSWORD = 'Password123';

interface SeedResult {
  userCreated: boolean;
  transactionsSeeded: boolean;
  mnemonicPath: string | null;
}

/**
 * Flush Redis rate limiter keys for the test user.
 * This prevents "too many requests" errors when running multiple org-mode tests.
 * Backend limits logins to 3/minute per email (ANONYMOUS_MINUTE_LIMIT=3).
 */
async function flushRateLimiter(): Promise<void> {
  const redisUrl = process.env.REDIS_URL || 'redis://localhost:6380';
  const redis = createClient({ url: redisUrl });

  try {
    await redis.connect();
    // Delete all throttler keys (pattern: {hash:throttler-name}:hits)
    const keys = await redis.keys('*:hits');
    if (keys.length > 0) {
      await redis.del(keys);
      console.log(`  Flushed ${keys.length} rate limiter keys from Redis`);
    } else {
      console.log('  No rate limiter keys to flush');
    }
  } catch (error) {
    // Redis might not be running - log but don't fail
    console.warn('  Warning: Could not flush Redis rate limiter:', (error as Error).message);
  } finally {
    await redis.disconnect();
  }
}

/**
 * Seed the PostgreSQL database with k6 test user and transactions.
 * Equivalent to running: npm run k6:seed:all
 *
 * This function:
 * 1. Creates the k6 test user if not exists
 * 2. Seeds transactions (sign, history, approve)
 * 3. Generates mnemonic for Account Setup import
 */
export async function seedOrgPerfData(): Promise<SeedResult> {
  const automationDir = path.resolve(__dirname, '../..');
  const mnemonicPath = path.join(__dirname, '../../k6/data/test-mnemonic.txt');

  console.log('Seeding org-mode performance test data...');

  try {
    // Step 0: Flush rate limiter to prevent "too many requests" errors
    await flushRateLimiter();

    // Step 1: Create test user (if not exists)
    console.log('  Step 1: Creating k6 test user...');
    execSync('npx tsx k6/helpers/seed-test-users.ts', {
      cwd: automationDir,
      stdio: 'inherit',
      env: {
        ...process.env,
        TEST_USER_EMAIL: K6_USER_EMAIL,
        TEST_USER_PASSWORD: K6_USER_PASSWORD,
      },
    });

    // Step 2: Seed transactions and generate mnemonic
    console.log('  Step 2: Seeding transactions...');
    execSync('npx tsx k6/helpers/seed-perf-data.ts', {
      cwd: automationDir,
      stdio: 'inherit',
      env: {
        ...process.env,
        TEST_USER_EMAIL: K6_USER_EMAIL,
      },
    });

    // Verify mnemonic was generated
    if (!fs.existsSync(mnemonicPath)) {
      throw new Error(`Mnemonic file not found at ${mnemonicPath}`);
    }

    console.log('  Org-mode data seeding complete!');

    return {
      userCreated: true,
      transactionsSeeded: true,
      mnemonicPath,
    };
  } catch (error) {
    console.error('Error seeding org-mode data:', error);
    throw error;
  }
}

/**
 * Read the mnemonic generated by the seed script.
 * Returns array of 24 words.
 */
export function readSeedMnemonic(): string[] {
  const mnemonicPath = path.join(__dirname, '../../k6/data/test-mnemonic.txt');

  if (!fs.existsSync(mnemonicPath)) {
    throw new Error(
      `Mnemonic file not found. Run seedOrgPerfData() first or: npm run k6:seed:all`,
    );
  }

  const mnemonic = fs.readFileSync(mnemonicPath, 'utf-8').trim();
  const words = mnemonic.split(' ');

  if (words.length !== 24) {
    throw new Error(`Invalid mnemonic: expected 24 words, got ${words.length}`);
  }

  return words;
}

/**
 * Check if org-mode seed data exists (quick check without re-seeding)
 */
export function isOrgDataSeeded(): boolean {
  const mnemonicPath = path.join(__dirname, '../../k6/data/test-mnemonic.txt');
  return fs.existsSync(mnemonicPath);
}
